"""Ensemble detection signals.

Each signal returns a float in [0.0, 1.0] where higher means *more likely
AI-generated*. The three signals are deliberately independent so that the
weighted scorer can reach an ensemble consensus rather than relying on a single
point of failure.

Signal 1 - LLM (Groq Llama-3.3-70b): semantic coherence / perplexity proxy.
Signal 2 - Stylometric: type-token ratio + sentence-length variance (pure Python).
Signal 3 - Metadata: inspects EXIF / structural markers for generator watermarks.
"""
import json
import os
import re
import statistics
from typing import Any

try:  # Groq is optional at import time so tests run without the dependency.
    from groq import Groq
except ImportError:  # pragma: no cover
    Groq = None


# --------------------------------------------------------------------- Signal 1
def llm_signal(text: str) -> float:
    """Score semantic coherence via Groq. Fails safe to 0.5 (Uncertain).

    Blind spot: may struggle with highly abstract poetry, where low coherence
    is intentional and human.
    """
    api_key = os.getenv("GROQ_API_KEY")
    if not text or not text.strip():
        return 0.5
    if Groq is None or not api_key or api_key == "your_groq_api_key_here":
        # No usable client -> fail safe to Uncertain rather than guessing.
        return 0.5

    model = os.getenv("GROQ_MODEL", "llama-3.3-70b-versatile")
    client = Groq(api_key=api_key)
    prompt = (
        "You are an AI-content detector. Estimate the probability that the "
        "following text was generated by a large language model. Consider "
        "uniformity of tone, low burstiness, generic phrasing and hyper-fluency. "
        "Respond ONLY with a JSON object: {\"ai_probability\": <float 0..1>}.\n\n"
        f"TEXT:\n{text[:4000]}"
    )
    try:
        resp = client.chat.completions.create(
            model=model,
            messages=[{"role": "user", "content": prompt}],
            temperature=0.0,
            response_format={"type": "json_object"},
        )
        data = json.loads(resp.choices[0].message.content)
        return _clamp(float(data.get("ai_probability", 0.5)))
    except Exception:
        # Fail-safe: API timeout / error maps to Uncertain, never to "Human".
        return 0.5


# --------------------------------------------------------------------- Signal 2
def stylometric_signal(text: str) -> float:
    """Measure type-token ratio and sentence-length variance.

    Human prose tends to have higher lexical diversity and higher "burstiness"
    (variance in sentence length). AI text trends toward uniform, mid-length
    sentences and lower diversity.

    Blind spot: can be fooled by deliberate, formulaic human writing.
    """
    if not text or not text.strip():
        return 0.5

    tokens = re.findall(r"\b\w+\b", text.lower())
    if len(tokens) < 5:
        return 0.5

    type_token_ratio = len(set(tokens)) / len(tokens)

    sentences = [s for s in re.split(r"[.!?]+", text) if s.strip()]
    lengths = [len(re.findall(r"\b\w+\b", s)) for s in sentences]
    variance = statistics.pvariance(lengths) if len(lengths) > 1 else 0.0

    # Normalise: low diversity -> AI-leaning; low variance -> AI-leaning.
    diversity_ai = _clamp(1.0 - (type_token_ratio - 0.3) / 0.5)
    burstiness_ai = _clamp(1.0 - variance / 40.0)

    return _clamp(0.5 * diversity_ai + 0.5 * burstiness_ai)


# --------------------------------------------------------------------- Signal 3
def metadata_signal(metadata: dict[str, Any] | None) -> float:
    """Inspect structural metadata for known AI-generator markers.

    Blind spot: metadata is easily stripped by platform uploads, so absence of
    a marker is weak evidence -> defaults toward Uncertain/Human-leaning.
    """
    if not metadata:
        return 0.4  # No metadata available: mild human lean, mostly uncertain.

    haystack = json.dumps(metadata).lower()
    ai_markers = [
        "dall-e", "dalle", "midjourney", "stable diffusion", "stable-diffusion",
        "firefly", "openai", "gpt", "sora", "runway", "c2pa", "ai-generated",
        "synthid", "leonardo.ai",
    ]
    if any(marker in haystack for marker in ai_markers):
        return 0.95

    # A "Software" field naming a normal camera/editor leans human.
    human_markers = ["camera", "iphone", "canon", "nikon", "lightroom", "gimp"]
    if any(marker in haystack for marker in human_markers):
        return 0.2

    return 0.4


def image_artifact_signal(caption: str) -> float:
    """Analyze the VLM image description for mentions of AI visual artifacts.

    Fails safe to 0.5 (Uncertain).
    """
    api_key = os.getenv("GROQ_API_KEY")
    if not caption or not caption.strip():
        return 0.5
    if Groq is None or not api_key or api_key == "your_groq_api_key_here":
        return 0.5

    model = os.getenv("GROQ_MODEL", "llama-3.3-70b-versatile")
    client = Groq(api_key=api_key)
    prompt = (
        "You are an AI-content detector. Analyze the following description of an image "
        "and estimate the probability that the image itself is AI-generated based on the "
        "description (e.g., look for mentions of visual artifacts, impossible geometry, "
        "malformed details, or unnatural/over-smooth features). "
        "Respond ONLY with a JSON object: {\"ai_probability\": <float 0..1>}.\n\n"
        f"IMAGE DESCRIPTION:\n{caption}"
    )
    try:
        resp = client.chat.completions.create(
            model=model,
            messages=[{"role": "user", "content": prompt}],
            temperature=0.0,
            response_format={"type": "json_object"},
        )
        data = json.loads(resp.choices[0].message.content)
        return _clamp(float(data.get("ai_probability", 0.5)))
    except Exception:
        return 0.5


def run_signals(text: str, metadata: dict[str, Any] | None = None, source: str = "text") -> dict[str, float]:
    """Run signals and return their raw scores, adapted to the source type."""
    if source == "image" and metadata and metadata.get("vlm_captioned"):
        # Extract the caption from the transcript text.
        # The text is formatted as: "[image transcript of '<name>'] <caption_text>"
        # or "[image transcript] <caption_text>"
        idx = text.find("] ")
        caption = text[idx + 2:] if idx != -1 else text
        
        return {
            "llm": image_artifact_signal(caption),
            "stylometric": 0.5,  # Ignored by weights for image
            "metadata": metadata_signal(metadata),
        }

    return {
        "llm": llm_signal(text),
        "stylometric": stylometric_signal(text),
        "metadata": metadata_signal(metadata),
    }


def _clamp(value: float, lo: float = 0.0, hi: float = 1.0) -> float:
    return max(lo, min(hi, value))

